
file:
  storage:
    path: /data/netup

#Eureka服务注册中心
eureka:
  instance:
    hostname: Eureka02 #服务注册中心IP地址
    port: 8083 #服务注册中心端口
    prefer-ip-address: true
    instanceId: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://Eureka01:${eureka.instance.port}/eureka/