server:
  port: 9084
file:
  storage:
    path: /Users/mayi/XIYU/temp

#Eureka服务注册中心
eureka:
  instance:
    hostname: localhost #服务注册中心IP地址
    prefer-ip-address: true
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://116.62.234.85:9083/eureka/