
file:
  storage:
    path: /data/netup

#Eureka服务注册中心
eureka:
  instance:
    preferIpAddress: true
    #这样写eureka服务注册中心会显示本机ip+端口号
    instanceId: ${spring.application.name}:${server.port}
    #这样写eureka服务注册中心会显示项目名和端口号
    #instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/,http://localhost:8084/eureka/  #集群注册中心地址