
server:
  port: 9087
file:
  storage:
    path: /Users/mayi/XIYU/temp

#Eureka注册
eureka:
  instance:
    preferIpAddress: true
    ip-address: localhost
    #这样写eureka服务注册中心会显示本机ip+端口号
    instanceId: ${spring.application.name}:${server.port}
    #这样写eureka服务注册中心会显示项目名和端口号
    #instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://116.62.234.85:9083/eureka/,http://116.62.234.85:9084/eureka/ #集群注册中心地址

#Mysql连接池配置
spring:
  application:
    name: provider-user
  datasource:
      url: jdbc:mysql://116.62.234.85:3306/liyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 15
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      loginUsername: admin
      loginPassword: admin
  activemq:
    broker-url: tcp://116.62.234.85:1616
    in-memory: true
    non-blocking-redelivery: false   #这意味着当启用此命令时，消息顺序不会被保留
    send-timeout: 0  # 等待消息发送响应的时间。设置为0等待永远。
    user: admin
    password: admin
  jms:
    pub-sub-domain: true #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置为true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.mayi.user.mapper



